# Generated by Django 2.1.4 on 2019-01-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puregainz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttraining',
            name='exercise',
            field=models.CharField(blank=True, choices=[('dl', 'Deadlift'), ('sq', 'Squat'), ('bp', 'Benchpress'), ('pd', 'Pulldown'), ('rw', 'Row')], max_length=2),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
