# Generated by Django 2.1.4 on 2019-01-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puregainz', '0002_auto_20190105_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weighttraining',
            old_name='reps',
            new_name='rep',
        ),
    ]
