# Generated by Django 2.1.4 on 2019-01-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puregainz', '0003_auto_20190105_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttraining',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='puregainz.Workout'),
        ),
    ]
