# Generated by Django 2.1.4 on 2019-01-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puregainz', '0004_auto_20190105_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttraining',
            name='rep',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='weighttraining',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
