# Generated by Django 2.1.4 on 2019-01-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puregainz', '0005_auto_20190105_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttraining',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='puregainz.Workout'),
        ),
    ]
