# Generated by Django 2.1.4 on 2019-01-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puregainz', '0006_auto_20190106_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttraining',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutChild', to='puregainz.Workout'),
        ),
    ]
