# Generated by Django 2.1.4 on 2019-01-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nasacomment',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='nasacomment',
            old_name='urls',
            new_name='url',
        ),
    ]
